### ISSUE TITLE
Can't see ticket history

### ISSUE THREAD

**Issue by AnitaBlake** [vimeo/zendesk-ticket-history#17]
Google Chrome 76.0.3809.132, Win 10 Pro (64)

Previously, you could see the total number of user tickets in the preview. Today the numbers are incorrect - they show the wrong amount, but the real amount is visible only if you open the user profile.

![image](http://dl4.joxi.net/drive/2019/09/16/0037/0568/2429496/96/b533e616a0.jpg)

![image](http://dl3.joxi.net/drive/2019/09/16/0037/0568/2429496/96/786941cc90.jpg)

**Comment by zenahirsch** [comment]
Hi @AnitaBlake, this is due to a recent app update (at Zendesk's request) that excludes [https://support.zendesk.com/hc/en-us/articles/203657756-About-ticket-archiving](archived tickets) from the display. This makes the app load faster, but I am still trying to decide if its a worthwhile trade-off. Let me know if you have any particular arguments one way or another.

**Comment by AnitaBlake** [comment]
Hi @zenahirsch!
Thanks for your reply.
Seeing the actual number of tickets is very important to us. Today, we repeatedly asked users for data that could be found in the ticket history, until we realized what happened to the application settings. Users remember that they sent us this data before and, of course, they get angry when we ask for this data again.
Support manager works very quickly and we does not have the ability to open each user’s profile, otherwise our speed will drop. Therefore, it is important for us to understand whether there have been tickets from the user before or not. If we do not see this, then this application is useless for us.

**Comment by kayleearielle** [comment]
Also extremely important for our workflow to have visibility into five most recent regardless of age – any potential to bring back the full view version?
