### ISSUE TITLE
Ticket history app not displaying tickets

### ISSUE THREAD

**Issue by cfassano** [vimeo/zendesk-ticket-history#18]
* Browser and operating system: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
* App version:  Version: 1.0.5, Framework Version: 2.0
* Description of issue or comments:
The app isn't displaying all tickets.  Sometimes it doesn't show anything.  Sometimes reloading the browser tab resolves the issue.  

* Link to screenshot:
This shows that the customer has 3 tickets. 1 open and 2 closed.
<img width="282" alt="Zendesk ticket history" src="https://user-images.githubusercontent.com/43358151/65981197-74750c80-e42d-11e9-92d7-a90c4d5b2aa2.png">
The app only shows the open ticket.
<img width="179" alt="ticket history app" src="https://user-images.githubusercontent.com/43358151/65981204-776ffd00-e42d-11e9-9478-2d6db2b5b1e1.png">

**Comment by zenahirsch** [comment]
This should be fixed with the latest version (1.0.6). Note that you'll have to go into the app settings and uncheck "Exclude archived tickets" before those tickets will start appearing. Read more about the change here: https://zenahirsch.com/blog/zendesk-ticket-history-v106-new-exclude-archived-tickets-option
