### ISSUE TITLE
Ticket History app history not displaying recent tickets

### ISSUE THREAD

**Issue by laurateichmiller** [vimeo/zendesk-ticket-history#19]
* **Browser and operating system:** Google Chrome Version 78.0.3904.70, macOS Mojave 10.14.6

* **App version:** Ticket History App Version: 1.0.5, Framework Version: 2.0

* **Description of issue or comments:** The Ticket History app is not displaying all recent tickets from customers. For the most recent instance of this, only 2 tickets were displayed for the customer in the app, but they have 3 that they've submitted this year alone. The two that are showing in the app are dated 10/30/19 and 7/31/19, and the one that isn't showing for this year is dated 5/29/19. Is there a cutoff for what counts as a "recent" ticket? Thanks for your help!

**Comment by zenahirsch** [comment]
This should be fixed with the latest version (1.0.6). Note that you'll have to go into the app settings and uncheck "Exclude archived tickets" before those tickets will start appearing. Read more about the change here: https://zenahirsch.com/blog/zendesk-ticket-history-v106-new-exclude-archived-tickets-option
