### ISSUE TITLE
Ticket History - where are they?! 

### ISSUE THREAD

**Issue by kayleearielle** [vimeo/zendesk-ticket-history#21]
Thank you for taking the time to reach out.

* Browser and operating system: 
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
MacOS Mojave 10.14.6
* App version: 
Version: 1.0.5
Framework Version: 2.0
Installed: August 7, 2018
* Description of issue or comments:
As other users have described, ticket history for closed/archived tickets is not being displayed even if it's within the top five most recent tickets. This is MANDATORY information for my teams success and adds an entirely manual step of clicking the customers name/email and checking for additional relevant history. 
* Link to screenshot:
<img width="914" alt="Screen Shot 2019-11-09 at 9 53 49 AM" src="https://user-images.githubusercontent.com/57961932/69176609-06b39b80-0ad4-11ea-8e5f-ee2e67701f2b.png">
<img width="600" alt="Screen Shot 2019-11-09 at 9 53 55 AM" src="https://user-images.githubusercontent.com/57961932/69176615-0a472280-0ad4-11ea-9c44-1e73abb7b721.png">

**Comment by zenahirsch** [comment]
This should be fixed with the latest version (1.0.6). Note that you'll have to go into the app settings and uncheck "Exclude archived tickets" before those tickets will start appearing. Read more about the change here: https://zenahirsch.com/blog/zendesk-ticket-history-v106-new-exclude-archived-tickets-option

**Comment by kayleearielle** [comment]
Thank you SO much! Truly appreciate this.
